### ISSUE TITLE
Failing spec:  ./spec/controllers/admin/category_controller_spec.rb

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#964] opened 2019-11-11 19:59 UTC
````
Failures:

  1) Admin::CategoriesController translations show the correct translation when 'I18n.locale :en'
     Failure/Error: expect(assigns(:category).name).to eq 'Science'

       expected: "Science"
            got: "Wissenschaft"

       (compared using ==)
     # ./spec/controllers/admin/category_controller_spec.rb:125:in `block (3 levels) in <main>'
````
Assumption: there are 2 translations for `locale: 'en'` and there could be a problem retrieving the right one. Why is it possible to create an extra translation for this locale? 

#<ActiveRecord::Associations::CollectionProxy [#<Category::Translation id: 3, category_id: 1, locale: "en", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: nil>, #<Category::Translation id: 2, category_id: 1, locale: "de", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: "Wissenschaft">, #<Category::Translation id: 1, category_id: 1, locale: "en", created_at: "2019-11-11 19:55:49", updated_at: "2019-11-11 19:55:49", name: "Science">]

**Comment by sabrina-ulbrich** [comment] 2019-11-13 22:39
Any progress here @zaziemo ? I asked Sven why a test can fail on one system but not on others. So, as far I understand it may depend on dependencies: when you have another version of ruby, postgres or something else running then others. Or maybe this failing test is caused by a a specific order of the tests: at the beginning rspec says "Randomized with seed ..." with a specific number, e.g. "Randomized with seed 2356". Question is, if this number is always the same when the test fails and if someone else runs the test in this specific order (with this number) if the other person get this failing test, too. Maybe that helps to localize the error.

**Comment by zaziemo** [comment] 2019-11-14 07:14
Hey @sabrina-ulbrich thanks for that perspective <3 I will have a closer look on these 2 points. Actually I encountered that problem after upgrading the ruby version. But now the specs also fail even in the branch with the old version (and I also check that the project is using the old version on my machine) :(

**Comment by sabrina-ulbrich** [comment] 2019-11-14 11:31
@zaziemo Do you try out to skip/comment out the part `before(:each)` in the `context 'translations'`? Inside this block is build another translation, but not in an appropriate way, so the spec `doesn't create extra translations` (it's commented out now) has 3 translations, but the new created one is nil. So, maybe this empty translation causes errors sometimes.

**Comment by zaziemo** [comment] 2019-11-25 18:33
@sabrina-ulbrich yes you are right. I have to check whether this test setting is useful at all. For the moment I can't reproduce this failing spec nowhere but on my private laptop ....

**Comment by netagonen** [comment] 2020-04-06 18:08
@zaziemo , is this really a bug or is it just in your machine?
Should we close the issue or remove the bug tag?

**Comment by zaziemo** [comment] 2020-04-11 10:08
@netagonen I don't know. Did you try it on yours? @sabrina-ulbrich couldn't reproduce it. Travis either. So if you can't reproduce it neither you could close it.

**Comment by sabrina-ulbrich** [comment] 2020-04-11 12:54
@zaziemo @netagonen Actually, after installing docker I get this error, too. Weird!

**Closed** 2024-11-02 11:56 UTC
Labels: bug
