### ISSUE TITLE
FAQ's: last paragraph

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#1057] opened 2020-03-05 17:41 UTC
FAQ's: the last paragraph, the bullet points are aligned left and the text is aligned to the center.
Suggestions:
Maybe this paragraph could be entirely aligned to the left?
Or the whole FAQ's aligned to the left?

![Screenshot from 2020-03-05 18-40-23](https://user-images.githubusercontent.com/22200510/76009022-d66ffb80-5f10-11ea-87d7-c2cd7db07018.png)

**Comment by zaziemo** [comment] 2020-03-09 20:02
I think it would be cool to have the whole FAQs left aligned. This was also the intended behaviour. But I think things changed when merged into the new design.

**Comment by sabrina-ulbrich** [comment] 2020-08-05 19:57
done :)

**Closed by sabrina-ulbrich** 2020-08-05 19:57 UTC
Labels: Frontend, bug
